### ISSUE TITLE
Blocked by CORS 

### ISSUE THREAD

**Issue by AndreScapinelli** [Benedicht/com.tivadar.best.documentation#7]
Hello guys. Iam having a problem with a webgl build. and I could find a solution for that yet.

The problem:
"... has been blocked by CORS policy: Response to preflight request doesn`t pass access control check:" No 'Acess-Control-Allow-Origin' header is present on the request resource.

I do not have that problem on a .exe and in the editor. 

![Imagem do WhatsApp de 2024-06-05 à(s) 13 33 30_83dfb7bf](https://github.com/Benedicht/com.tivadar.best.documentation/assets/139276203/85fbb797-ddae-40c5-a629-624749687e25)

**Comment by Benedicht** [comment]
CORS is an browser enforced security feature this is why the requests are failing only in a WebGL build.
It's also requires properly set up headers from the server, it can't be 'fixed' from the client side.

You can find quite a lot of good resources about CORS:
- https://aws.amazon.com/what-is/cross-origin-resource-sharing/
- https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/
